import AsyncStorage from "@react-native-async-storage/async-storage";
import React, { createContext, useCallback, useContext, useEffect, useState } from "react";
import { useColorScheme } from "react-native";

export type ThemeMode = "system" | "light" | "dark";
export type Language =
  | "en" | "tr" | "es" | "de" | "fr" | "ar" | "ru" | "zh"
  | "uz" | "kk" | "ky" | "tg" | "tk" | "az"
  | "ja" | "ko" | "pt" | "it" | "hi" | "id";

export const LANGUAGES: { code: Language; label: string; native: string; flag: string }[] = [
  { code: "en", label: "English",    native: "English",          flag: "🇬🇧" },
  { code: "ru", label: "Russian",    native: "Русский",          flag: "🇷🇺" },
  { code: "zh", label: "Chinese",    native: "中文",              flag: "🇨🇳" },
  { code: "ar", label: "Arabic",     native: "العربية",           flag: "🇸🇦" },
  { code: "hi", label: "Hindi",      native: "हिन्दी",             flag: "🇮🇳" },
  { code: "es", label: "Spanish",    native: "Español",          flag: "🇪🇸" },
  { code: "fr", label: "French",     native: "Français",         flag: "🇫🇷" },
  { code: "de", label: "German",     native: "Deutsch",          flag: "🇩🇪" },
  { code: "pt", label: "Portuguese", native: "Português",        flag: "🇧🇷" },
  { code: "it", label: "Italian",    native: "Italiano",         flag: "🇮🇹" },
  { code: "tr", label: "Turkish",    native: "Türkçe",           flag: "🇹🇷" },
  { code: "az", label: "Azerbaijani",native: "Azərbaycanca",     flag: "🇦🇿" },
  { code: "ja", label: "Japanese",   native: "日本語",             flag: "🇯🇵" },
  { code: "ko", label: "Korean",     native: "한국어",             flag: "🇰🇷" },
  { code: "id", label: "Indonesian", native: "Bahasa Indonesia", flag: "🇮🇩" },
  { code: "uz", label: "Uzbek",      native: "O'zbekcha",        flag: "🇺🇿" },
  { code: "kk", label: "Kazakh",     native: "Қазақша",          flag: "🇰🇿" },
  { code: "ky", label: "Kyrgyz",     native: "Кыргызча",         flag: "🇰🇬" },
  { code: "tg", label: "Tajik",      native: "Тоҷикӣ",           flag: "🇹🇯" },
  { code: "tk", label: "Turkmen",    native: "Türkmençe",        flag: "🇹🇲" },
];

export const LANGUAGE_LOCALIZED_NAMES: Record<Language, Record<Language, string>> = {
  en: { en:"English",      ru:"Английский",     zh:"英语",           ar:"الإنجليزية",   hi:"अंग्रेज़ी",    es:"Inglés",        fr:"Anglais",          de:"Englisch",          pt:"Inglês",         it:"Inglese",        tr:"İngilizce",      az:"İngilis dili",        ja:"英語",           ko:"영어",         id:"Bahasa Inggris",   uz:"Inglizcha",     kk:"Ағылшынша",     ky:"Англисча",     tg:"Забони англисӣ",    tk:"Iňlisçe"         },
  ru: { en:"Russian",      ru:"Русский",         zh:"俄语",           ar:"الروسية",      hi:"रूसी",         es:"Ruso",          fr:"Russe",            de:"Russisch",          pt:"Russo",          it:"Russo",          tr:"Rusça",          az:"Rus dili",            ja:"ロシア語",       ko:"러시아어",      id:"Bahasa Rusia",     uz:"Ruscha",        kk:"Орысша",        ky:"Орусча",       tg:"Забони русӣ",       tk:"Rusça"           },
  zh: { en:"Chinese",      ru:"Китайский",       zh:"中文",           ar:"الصينية",      hi:"चीनी",         es:"Chino",         fr:"Chinois",          de:"Chinesisch",        pt:"Chinês",         it:"Cinese",         tr:"Çince",          az:"Çin dili",            ja:"中国語",         ko:"중국어",        id:"Bahasa Cina",      uz:"Xitoycha",      kk:"Қытайша",       ky:"Кытайча",      tg:"Забони чинӣ",       tk:"Hytaýça"         },
  ar: { en:"Arabic",       ru:"Арабский",        zh:"阿拉伯语",        ar:"العربية",      hi:"अरबी",         es:"Árabe",         fr:"Arabe",            de:"Arabisch",          pt:"Árabe",          it:"Arabo",          tr:"Arapça",         az:"Ərəb dili",           ja:"アラビア語",     ko:"아랍어",        id:"Bahasa Arab",      uz:"Arabcha",       kk:"Арабша",        ky:"Арабча",       tg:"Забони арабӣ",      tk:"Arapça"          },
  hi: { en:"Hindi",        ru:"Хинди",           zh:"印地语",         ar:"الهندية",      hi:"हिन्दी",        es:"Hindi",         fr:"Hindi",            de:"Hindi",             pt:"Hindi",          it:"Hindi",          tr:"Hintçe",         az:"Hind dili",           ja:"ヒンディー語",   ko:"힌디어",        id:"Bahasa Hindi",     uz:"Hindcha",       kk:"Хиндіше",       ky:"Хиндиче",      tg:"Забони хиндӣ",      tk:"Hindi"           },
  es: { en:"Spanish",      ru:"Испанский",       zh:"西班牙语",        ar:"الإسبانية",    hi:"स्पेनिश",      es:"Español",       fr:"Espagnol",         de:"Spanisch",          pt:"Espanhol",       it:"Spagnolo",       tr:"İspanyolca",     az:"İspan dili",          ja:"スペイン語",     ko:"스페인어",      id:"Bahasa Spanyol",   uz:"Ispancha",      kk:"Испанша",       ky:"Испанча",      tg:"Забони испанӣ",     tk:"Ispança"         },
  fr: { en:"French",       ru:"Французский",     zh:"法语",           ar:"الفرنسية",     hi:"फ्रेंच",        es:"Francés",       fr:"Français",         de:"Französisch",       pt:"Francês",        it:"Francese",       tr:"Fransızca",      az:"Fransız dili",        ja:"フランス語",     ko:"프랑스어",      id:"Bahasa Prancis",   uz:"Fransuzcha",    kk:"Французша",     ky:"Французча",    tg:"Забони фаронсавӣ",  tk:"Fransuzça"       },
  de: { en:"German",       ru:"Немецкий",        zh:"德语",           ar:"الألمانية",    hi:"जर्मन",         es:"Alemán",        fr:"Allemand",         de:"Deutsch",           pt:"Alemão",         it:"Tedesco",        tr:"Almanca",        az:"Alman dili",          ja:"ドイツ語",       ko:"독일어",        id:"Bahasa Jerman",    uz:"Nemischa",      kk:"Немісше",       ky:"Немисче",      tg:"Забони олмонӣ",     tk:"Nemesçe"         },
  pt: { en:"Portuguese",   ru:"Португальский",   zh:"葡萄牙语",        ar:"البرتغالية",   hi:"पुर्तगाली",    es:"Portugués",     fr:"Portugais",        de:"Portugiesisch",     pt:"Português",      it:"Portoghese",     tr:"Portekizce",     az:"Portuqal dili",       ja:"ポルトガル語",   ko:"포르투갈어",    id:"Bahasa Portugis",  uz:"Portugalcha",   kk:"Португалша",    ky:"Португалча",   tg:"Забони португалӣ",  tk:"Portugisçe"      },
  it: { en:"Italian",      ru:"Итальянский",     zh:"意大利语",        ar:"الإيطالية",    hi:"इतालवी",        es:"Italiano",      fr:"Italien",          de:"Italienisch",       pt:"Italiano",       it:"Italiano",       tr:"İtalyanca",      az:"İtalyan dili",        ja:"イタリア語",     ko:"이탈리아어",    id:"Bahasa Italia",    uz:"Italyancha",    kk:"Итальянша",     ky:"Италиянча",    tg:"Забони италиявӣ",   tk:"Italýança"       },
  tr: { en:"Turkish",      ru:"Турецкий",        zh:"土耳其语",        ar:"التركية",      hi:"तुर्की",        es:"Turco",         fr:"Turc",             de:"Türkisch",          pt:"Turco",          it:"Turco",          tr:"Türkçe",         az:"Türk dili",           ja:"トルコ語",       ko:"터키어",        id:"Bahasa Turki",     uz:"Turkcha",       kk:"Түрікше",       ky:"Түркчө",       tg:"Забони туркӣ",      tk:"Türkçe"          },
  az: { en:"Azerbaijani",  ru:"Азербайджанский", zh:"阿塞拜疆语",      ar:"الأذربيجانية", hi:"अज़रबैजानी",   es:"Azerbaiyano",   fr:"Azerbaïdjanais",   de:"Aserbaidschanisch", pt:"Azerbaijano",    it:"Azerbaigiano",   tr:"Azerbaycanca",   az:"Azərbaycanca",        ja:"アゼルバイジャン語",ko:"아제르바이잔어", id:"Bahasa Azerbaijan", uz:"Ozarbayjoncha", kk:"Әзірбайжанша",  ky:"Азербайжанча", tg:"Забони озарбойҷонӣ",tk:"Azerbaýjança"    },
  ja: { en:"Japanese",     ru:"Японский",        zh:"日语",           ar:"اليابانية",    hi:"जापानी",        es:"Japonés",       fr:"Japonais",         de:"Japanisch",         pt:"Japonês",        it:"Giapponese",     tr:"Japonca",        az:"Yapon dili",          ja:"日本語",         ko:"일본어",        id:"Bahasa Jepang",    uz:"Yaponcha",      kk:"Жапонша",       ky:"Жапонча",      tg:"Забони ҷопонӣ",     tk:"Ýaponça"         },
  ko: { en:"Korean",       ru:"Корейский",       zh:"韩语",           ar:"الكورية",      hi:"कोरियाई",       es:"Coreano",       fr:"Coréen",           de:"Koreanisch",        pt:"Coreano",        it:"Coreano",        tr:"Korece",         az:"Koreya dili",         ja:"韓国語",         ko:"한국어",        id:"Bahasa Korea",     uz:"Koreyacha",     kk:"Корейше",       ky:"Корейче",      tg:"Забони кореягӣ",    tk:"Koreýçe"         },
  id: { en:"Indonesian",   ru:"Индонезийский",   zh:"印尼语",         ar:"الإندونيسية",  hi:"इंडोनेशियाई",  es:"Indonesio",     fr:"Indonésien",       de:"Indonesisch",       pt:"Indonésio",      it:"Indonesiano",    tr:"Endonezce",      az:"İndoneziya dili",     ja:"インドネシア語", ko:"인도네시아어",  id:"Bahasa Indonesia",  uz:"Indoneziyacha", kk:"Индонезияша",   ky:"Индонезиялык", tg:"Забони индонезӣ",   tk:"Indoneziýaça"    },
  uz: { en:"Uzbek",        ru:"Узбекский",       zh:"乌兹别克语",      ar:"الأوزبكية",    hi:"उज़्बेक",       es:"Uzbeko",        fr:"Ouzbek",           de:"Usbekisch",         pt:"Uzbeque",        it:"Uzbeko",         tr:"Özbekçe",        az:"Özbək dili",          ja:"ウズベク語",     ko:"우즈베크어",    id:"Bahasa Uzbek",     uz:"O'zbekcha",     kk:"Өзбекше",       ky:"Өзбекче",      tg:"Забони ӯзбекӣ",     tk:"Özbek dili"      },
  kk: { en:"Kazakh",       ru:"Казахский",       zh:"哈萨克语",        ar:"الكازاخية",    hi:"कज़ाख़",        es:"Kazajo",        fr:"Kazakh",           de:"Kasachisch",        pt:"Cazaque",        it:"Kazako",         tr:"Kazakça",        az:"Qazax dili",          ja:"カザフ語",       ko:"카자흐어",      id:"Bahasa Kazakh",    uz:"Qozoqcha",      kk:"Қазақша",       ky:"Казакча",      tg:"Забони қазоқӣ",     tk:"Gazakça"         },
  ky: { en:"Kyrgyz",       ru:"Кыргызский",      zh:"柯尔克孜语",      ar:"القيرغيزية",   hi:"किर्गिज़",      es:"Kirguís",       fr:"Kirghiz",          de:"Kirgisisch",        pt:"Quirguiz",       it:"Kirghizo",       tr:"Kırgızca",       az:"Qırğız dili",         ja:"キルギス語",     ko:"키르기스어",    id:"Bahasa Kyrgyz",    uz:"Qirg'izcha",    kk:"Қырғызша",      ky:"Кыргызча",     tg:"Забони қирғизӣ",    tk:"Gyrgyzça"        },
  tg: { en:"Tajik",        ru:"Таджикский",      zh:"塔吉克语",        ar:"الطاجيكية",    hi:"ताजिक",         es:"Tayiko",        fr:"Tadjik",           de:"Tadschikisch",      pt:"Tajique",        it:"Tagico",         tr:"Tacikçe",        az:"Tacik dili",          ja:"タジク語",       ko:"타지크어",      id:"Bahasa Tajik",     uz:"Tojikcha",      kk:"Тәжікше",       ky:"Тажикче",      tg:"Тоҷикӣ",            tk:"Täjikçe"         },
  tk: { en:"Turkmen",      ru:"Туркменский",     zh:"土库曼语",        ar:"التركمانية",   hi:"तुर्कमेन",      es:"Turcomano",     fr:"Turkmène",         de:"Turkmenisch",       pt:"Turcomeno",      it:"Turkmeno",       tr:"Türkmence",      az:"Türkmən dili",        ja:"トルクメン語",   ko:"투르크멘어",    id:"Bahasa Turkmen",   uz:"Turkmancha",    kk:"Түрікменше",    ky:"Түркмөнчө",    tg:"Забони туркманӣ",   tk:"Türkmençe"       },
};

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    plan: "Plan", progress: "Progress", community: "Community", profile: "Profile",
    daily: "Daily", weekly: "Weekly", monthly: "Monthly", yearly: "Yearly",
    noTasks: "No tasks yet", addFirst: "Tap + to add your first task",
    inProgress: "In Progress", completed: "Completed",
    tasksCompleted: "tasks completed", of: "of",
    dailyMotivation: "Daily Motivation", all: "All",
    achievements: "Achievements", communityChallenges: "Community Challenges",
    notifications: "Notifications", pushNotifications: "Push Notifications",
    alarmSound: "Alarm Sound", appearance: "Appearance",
    theme: "Theme", language: "Language", partners: "Partners",
    data: "Data", clearAllData: "Clear All Data",
    tasksDone: "Tasks Done", dayStreak: "Day Streak", completion: "Completion",
    chooseTheme: "Choose Theme", chooseLanguage: "Choose Language",
    addTask: "Add Task", save: "Save", cancel: "Cancel",
    noChallenges: "No challenges joined yet.\nVisit Community to join one!",
    communitySubtitle: "Share your wins, find your tribe",
    newPost: "New Post", activityFeed: "Activity Feed", challenges: "Challenges",
    participants: "participants", joined: "Joined", join: "Join",
    newPostPlaceholder: "Share your win, progress, or tip...",
    category: "Category", publishPost: "Publish Post",
    comments: "Comments", noCommentsYet: "No comments yet. Be the first!",
    writeComment: "Write a comment...", you: "You", justNow: "Just now",
    progressSubtitle: "Track your productivity over time",
    overallCompletion: "Overall Completion",
    done: "Done", remaining: "Remaining", total: "Total",
    byCategory: "By Category", aiInsights: "AI Insights",
    noTaskData: "No task data yet for this period.\nAdd tasks in the Plan tab to see your progress!",
  },
  ru: {
    plan: "План", progress: "Прогресс", community: "Сообщество", profile: "Профиль",
    daily: "Ежедневно", weekly: "Еженедельно", monthly: "Ежемесячно", yearly: "Ежегодно",
    noTasks: "Задач пока нет", addFirst: "Нажмите + чтобы добавить первую задачу",
    inProgress: "В Процессе", completed: "Завершено",
    tasksCompleted: "задач выполнено", of: "из",
    dailyMotivation: "Мотивация дня", all: "Все",
    achievements: "Достижения", communityChallenges: "Вызовы сообщества",
    notifications: "Уведомления", pushNotifications: "Push-уведомления",
    alarmSound: "Звук будильника", appearance: "Внешний вид",
    theme: "Тема", language: "Язык", partners: "Партнёры",
    data: "Данные", clearAllData: "Очистить всё",
    tasksDone: "Выполнено", dayStreak: "Дней подряд", completion: "Процент",
    chooseTheme: "Выбор темы", chooseLanguage: "Выбор языка",
    addTask: "Добавить задачу", save: "Сохранить", cancel: "Отмена",
    noChallenges: "Вы ещё не участвуете в вызовах.\nПосетите раздел Сообщество!",
    communitySubtitle: "Делитесь успехами, находите единомышленников",
    newPost: "Новый пост", activityFeed: "Лента", challenges: "Вызовы",
    participants: "участников", joined: "Вступил", join: "Вступить",
    newPostPlaceholder: "Поделитесь победой, прогрессом или советом...",
    category: "Категория", publishPost: "Опубликовать",
    comments: "Комментарии", noCommentsYet: "Пока нет комментариев. Будьте первым!",
    writeComment: "Написать комментарий...", you: "Вы", justNow: "Только что",
    progressSubtitle: "Отслеживайте продуктивность",
    overallCompletion: "Общее выполнение",
    done: "Готово", remaining: "Осталось", total: "Всего",
    byCategory: "По категориям", aiInsights: "ИИ-аналитика",
    noTaskData: "Данных за этот период нет.\nДобавьте задачи во вкладке «План»!",
  },
  zh: {
    plan: "计划", progress: "进度", community: "社区", profile: "我的",
    daily: "每日", weekly: "每周", monthly: "每月", yearly: "每年",
    noTasks: "暂无任务", addFirst: "点击 + 添加第一个任务",
    inProgress: "进行中", completed: "已完成",
    tasksCompleted: "个任务已完成", of: "/",
    dailyMotivation: "每日激励", all: "全部",
    achievements: "成就", communityChallenges: "社区挑战",
    notifications: "通知", pushNotifications: "推送通知",
    alarmSound: "闹钟声音", appearance: "外观",
    theme: "主题", language: "语言", partners: "合作伙伴",
    data: "数据", clearAllData: "清除所有数据",
    tasksDone: "已完成任务", dayStreak: "连续天数", completion: "完成率",
    chooseTheme: "选择主题", chooseLanguage: "选择语言",
    addTask: "添加任务", save: "保存", cancel: "取消",
    noChallenges: "尚未加入任何挑战。\n前往社区加入！",
    communitySubtitle: "分享进步，找到同路人",
    newPost: "发帖", activityFeed: "动态", challenges: "挑战",
    participants: "人参与", joined: "已加入", join: "加入",
    newPostPlaceholder: "分享你的成就、进度或技巧...",
    category: "分类", publishPost: "发布",
    comments: "评论", noCommentsYet: "暂无评论，来第一个留言吧！",
    writeComment: "写评论...", you: "我", justNow: "刚刚",
    progressSubtitle: "追踪你的效率变化",
    overallCompletion: "总体完成率",
    done: "完成", remaining: "剩余", total: "总计",
    byCategory: "按分类", aiInsights: "AI 洞察",
    noTaskData: "该时段暂无任务数据。\n在「计划」中添加任务！",
  },
  ar: {
    plan: "خطة", progress: "التقدم", community: "المجتمع", profile: "الملف",
    daily: "يومي", weekly: "أسبوعي", monthly: "شهري", yearly: "سنوي",
    noTasks: "لا توجد مهام بعد", addFirst: "اضغط + لإضافة مهمتك الأولى",
    inProgress: "قيد التنفيذ", completed: "مكتمل",
    tasksCompleted: "مهام مكتملة", of: "من",
    dailyMotivation: "الإلهام اليومي", all: "الكل",
    achievements: "الإنجازات", communityChallenges: "تحديات المجتمع",
    notifications: "الإشعارات", pushNotifications: "الإشعارات الفورية",
    alarmSound: "صوت المنبه", appearance: "المظهر",
    theme: "السمة", language: "اللغة", partners: "الشركاء",
    data: "البيانات", clearAllData: "مسح كل البيانات",
    tasksDone: "المهام المنجزة", dayStreak: "أيام متتالية", completion: "نسبة الإتمام",
    chooseTheme: "اختر السمة", chooseLanguage: "اختر اللغة",
    addTask: "إضافة مهمة", save: "حفظ", cancel: "إلغاء",
    noChallenges: "لم تنضم إلى أي تحدي بعد.\nزر المجتمع للانضمام!",
    communitySubtitle: "شارك انتصاراتك وابحث عن مجتمعك",
    newPost: "منشور جديد", activityFeed: "التغذية", challenges: "التحديات",
    participants: "مشارك", joined: "انضممت", join: "انضم",
    newPostPlaceholder: "شارك إنجازك، تقدمك، أو نصيحتك...",
    category: "الفئة", publishPost: "نشر",
    comments: "التعليقات", noCommentsYet: "لا تعليقات بعد. كن الأول!",
    writeComment: "اكتب تعليقاً...", you: "أنت", justNow: "الآن",
    progressSubtitle: "تتبع إنتاجيتك عبر الزمن",
    overallCompletion: "الإتمام الكلي",
    done: "تم", remaining: "متبقي", total: "الكلي",
    byCategory: "حسب الفئة", aiInsights: "رؤى الذكاء الاصطناعي",
    noTaskData: "لا توجد بيانات لهذه الفترة.\nأضف مهاماً في تبويب الخطة!",
  },
  hi: {
    plan: "योजना", progress: "प्रगति", community: "समुदाय", profile: "प्रोफ़ाइल",
    daily: "दैनिक", weekly: "साप्ताहिक", monthly: "मासिक", yearly: "वार्षिक",
    noTasks: "अभी कोई कार्य नहीं", addFirst: "+ दबाएं और पहला कार्य जोड़ें",
    inProgress: "जारी है", completed: "पूर्ण",
    tasksCompleted: "कार्य पूर्ण", of: "में से",
    dailyMotivation: "दैनिक प्रेरणा", all: "सभी",
    achievements: "उपलब्धियाँ", communityChallenges: "सामुदायिक चुनौतियाँ",
    notifications: "सूचनाएं", pushNotifications: "पुश नोटिफिकेशन",
    alarmSound: "अलार्म ध्वनि", appearance: "रूप-रंग",
    theme: "थीम", language: "भाषा", partners: "साझेदार",
    data: "डेटा", clearAllData: "सारा डेटा हटाएं",
    tasksDone: "कार्य हुए", dayStreak: "दिन की लकीर", completion: "पूर्णता",
    chooseTheme: "थीम चुनें", chooseLanguage: "भाषा चुनें",
    addTask: "कार्य जोड़ें", save: "सहेजें", cancel: "रद्द करें",
    noChallenges: "अभी कोई चुनौती नहीं जोड़ी।\nसमुदाय पर जाएं!",
    communitySubtitle: "अपनी जीत साझा करें, अपना समूह खोजें",
    newPost: "नई पोस्ट", activityFeed: "गतिविधि", challenges: "चुनौतियाँ",
    participants: "प्रतिभागी", joined: "शामिल हुए", join: "शामिल हों",
    newPostPlaceholder: "अपनी जीत, प्रगति या सुझाव साझा करें...",
    category: "श्रेणी", publishPost: "प्रकाशित करें",
    comments: "टिप्पणियाँ", noCommentsYet: "अभी कोई टिप्पणी नहीं। पहले लिखें!",
    writeComment: "टिप्पणी लिखें...", you: "आप", justNow: "अभी",
    progressSubtitle: "समय के साथ उत्पादकता ट्रैक करें",
    overallCompletion: "कुल पूर्णता",
    done: "हो गया", remaining: "शेष", total: "कुल",
    byCategory: "श्रेणी अनुसार", aiInsights: "AI अंतर्दृष्टि",
    noTaskData: "इस अवधि का कोई डेटा नहीं।\nप्लान टैब में कार्य जोड़ें!",
  },
  es: {
    plan: "Plan", progress: "Progreso", community: "Comunidad", profile: "Perfil",
    daily: "Diario", weekly: "Semanal", monthly: "Mensual", yearly: "Anual",
    noTasks: "Sin tareas aún", addFirst: "Toca + para agregar tu primera tarea",
    inProgress: "En Progreso", completed: "Completado",
    tasksCompleted: "tareas completadas", of: "de",
    dailyMotivation: "Motivación diaria", all: "Todo",
    achievements: "Logros", communityChallenges: "Retos comunitarios",
    notifications: "Notificaciones", pushNotifications: "Notificaciones push",
    alarmSound: "Sonido de alarma", appearance: "Apariencia",
    theme: "Tema", language: "Idioma", partners: "Socios",
    data: "Datos", clearAllData: "Borrar todos los datos",
    tasksDone: "Tareas hechas", dayStreak: "Racha de días", completion: "Completado",
    chooseTheme: "Elegir tema", chooseLanguage: "Elegir idioma",
    addTask: "Añadir tarea", save: "Guardar", cancel: "Cancelar",
    noChallenges: "Aún no te has unido a ningún reto.\n¡Visita Comunidad!",
    communitySubtitle: "Comparte tus logros, encuentra tu tribu",
    newPost: "Nueva publicación", activityFeed: "Actividad", challenges: "Retos",
    participants: "participantes", joined: "Unido", join: "Unirse",
    newPostPlaceholder: "Comparte tu logro, progreso o consejo...",
    category: "Categoría", publishPost: "Publicar",
    comments: "Comentarios", noCommentsYet: "Sin comentarios aún. ¡Sé el primero!",
    writeComment: "Escribe un comentario...", you: "Tú", justNow: "Ahora",
    progressSubtitle: "Sigue tu productividad a lo largo del tiempo",
    overallCompletion: "Completado general",
    done: "Hecho", remaining: "Restante", total: "Total",
    byCategory: "Por categoría", aiInsights: "Análisis IA",
    noTaskData: "Sin datos para este período.\n¡Agrega tareas en la pestaña Plan!",
  },
  fr: {
    plan: "Plan", progress: "Progrès", community: "Communauté", profile: "Profil",
    daily: "Quotidien", weekly: "Hebdomadaire", monthly: "Mensuel", yearly: "Annuel",
    noTasks: "Pas encore de tâches", addFirst: "Appuyez sur + pour ajouter votre première tâche",
    inProgress: "En Cours", completed: "Terminé",
    tasksCompleted: "tâches terminées", of: "sur",
    dailyMotivation: "Motivation du jour", all: "Tout",
    achievements: "Succès", communityChallenges: "Défis communautaires",
    notifications: "Notifications", pushNotifications: "Notifications push",
    alarmSound: "Son d'alarme", appearance: "Apparence",
    theme: "Thème", language: "Langue", partners: "Partenaires",
    data: "Données", clearAllData: "Effacer toutes les données",
    tasksDone: "Tâches faites", dayStreak: "Jours consécutifs", completion: "Achèvement",
    chooseTheme: "Choisir un thème", chooseLanguage: "Choisir une langue",
    addTask: "Ajouter une tâche", save: "Enregistrer", cancel: "Annuler",
    noChallenges: "Aucun défi rejoint.\nVisitez Communauté!",
    communitySubtitle: "Partagez vos victoires, trouvez votre tribu",
    newPost: "Nouveau post", activityFeed: "Fil d'activité", challenges: "Défis",
    participants: "participants", joined: "Rejoint", join: "Rejoindre",
    newPostPlaceholder: "Partagez votre victoire, progrès ou conseil...",
    category: "Catégorie", publishPost: "Publier",
    comments: "Commentaires", noCommentsYet: "Pas encore de commentaires. Soyez le premier !",
    writeComment: "Écrire un commentaire...", you: "Vous", justNow: "À l'instant",
    progressSubtitle: "Suivez votre productivité dans le temps",
    overallCompletion: "Achèvement global",
    done: "Fait", remaining: "Restant", total: "Total",
    byCategory: "Par catégorie", aiInsights: "Analyses IA",
    noTaskData: "Pas de données pour cette période.\nAjoutez des tâches dans l'onglet Plan !",
  },
  de: {
    plan: "Plan", progress: "Fortschritt", community: "Gemeinschaft", profile: "Profil",
    daily: "Täglich", weekly: "Wöchentlich", monthly: "Monatlich", yearly: "Jährlich",
    noTasks: "Noch keine Aufgaben", addFirst: "Tippe auf +, um deine erste Aufgabe hinzuzufügen",
    inProgress: "In Bearbeitung", completed: "Abgeschlossen",
    tasksCompleted: "Aufgaben erledigt", of: "von",
    dailyMotivation: "Tägliche Motivation", all: "Alle",
    achievements: "Erfolge", communityChallenges: "Community-Herausforderungen",
    notifications: "Benachrichtigungen", pushNotifications: "Push-Benachrichtigungen",
    alarmSound: "Alarmton", appearance: "Erscheinungsbild",
    theme: "Design", language: "Sprache", partners: "Partner",
    data: "Daten", clearAllData: "Alle Daten löschen",
    tasksDone: "Erledigt", dayStreak: "Tages-Streak", completion: "Abschluss",
    chooseTheme: "Design wählen", chooseLanguage: "Sprache wählen",
    addTask: "Aufgabe hinzufügen", save: "Speichern", cancel: "Abbrechen",
    noChallenges: "Noch keine Herausforderungen.\nBesuche die Gemeinschaft!",
    communitySubtitle: "Teile deine Erfolge, finde dein Team",
    newPost: "Neuer Beitrag", activityFeed: "Aktivitäten", challenges: "Herausforderungen",
    participants: "Teilnehmer", joined: "Beigetreten", join: "Beitreten",
    newPostPlaceholder: "Teile deinen Erfolg, Fortschritt oder Tipp...",
    category: "Kategorie", publishPost: "Veröffentlichen",
    comments: "Kommentare", noCommentsYet: "Noch keine Kommentare. Sei der Erste!",
    writeComment: "Kommentar schreiben...", you: "Du", justNow: "Gerade eben",
    progressSubtitle: "Verfolge deine Produktivität",
    overallCompletion: "Gesamtabschluss",
    done: "Erledigt", remaining: "Verbleibend", total: "Gesamt",
    byCategory: "Nach Kategorie", aiInsights: "KI-Analyse",
    noTaskData: "Keine Daten für diesen Zeitraum.\nFüge Aufgaben im Plan-Tab hinzu!",
  },
  pt: {
    plan: "Plano", progress: "Progresso", community: "Comunidade", profile: "Perfil",
    daily: "Diário", weekly: "Semanal", monthly: "Mensal", yearly: "Anual",
    noTasks: "Nenhuma tarefa ainda", addFirst: "Toque em + para adicionar sua primeira tarefa",
    inProgress: "Em Andamento", completed: "Concluído",
    tasksCompleted: "tarefas concluídas", of: "de",
    dailyMotivation: "Motivação diária", all: "Todos",
    achievements: "Conquistas", communityChallenges: "Desafios da comunidade",
    notifications: "Notificações", pushNotifications: "Notificações push",
    alarmSound: "Som do alarme", appearance: "Aparência",
    theme: "Tema", language: "Idioma", partners: "Parceiros",
    data: "Dados", clearAllData: "Limpar todos os dados",
    tasksDone: "Tarefas feitas", dayStreak: "Dias consecutivos", completion: "Conclusão",
    chooseTheme: "Escolher tema", chooseLanguage: "Escolher idioma",
    addTask: "Adicionar tarefa", save: "Salvar", cancel: "Cancelar",
    noChallenges: "Nenhum desafio ainda.\nVisite a Comunidade!",
    communitySubtitle: "Compartilhe suas vitórias, encontre sua tribo",
    newPost: "Nova publicação", activityFeed: "Atividade", challenges: "Desafios",
    participants: "participantes", joined: "Participando", join: "Participar",
    newPostPlaceholder: "Compartilhe sua vitória, progresso ou dica...",
    category: "Categoria", publishPost: "Publicar",
    comments: "Comentários", noCommentsYet: "Sem comentários ainda. Seja o primeiro!",
    writeComment: "Escreva um comentário...", you: "Você", justNow: "Agora",
    progressSubtitle: "Acompanhe sua produtividade ao longo do tempo",
    overallCompletion: "Conclusão geral",
    done: "Feito", remaining: "Restante", total: "Total",
    byCategory: "Por categoria", aiInsights: "Análises IA",
    noTaskData: "Sem dados para este período.\nAdicione tarefas na aba Plano!",
  },
  it: {
    plan: "Piano", progress: "Progresso", community: "Comunità", profile: "Profilo",
    daily: "Giornaliero", weekly: "Settimanale", monthly: "Mensile", yearly: "Annuale",
    noTasks: "Nessuna attività ancora", addFirst: "Premi + per aggiungere la tua prima attività",
    inProgress: "In Corso", completed: "Completato",
    tasksCompleted: "attività completate", of: "di",
    dailyMotivation: "Motivazione del giorno", all: "Tutto",
    achievements: "Traguardi", communityChallenges: "Sfide della comunità",
    notifications: "Notifiche", pushNotifications: "Notifiche push",
    alarmSound: "Suono sveglia", appearance: "Aspetto",
    theme: "Tema", language: "Lingua", partners: "Partner",
    data: "Dati", clearAllData: "Cancella tutti i dati",
    tasksDone: "Attività fatte", dayStreak: "Giorni consecutivi", completion: "Completamento",
    chooseTheme: "Scegli tema", chooseLanguage: "Scegli lingua",
    addTask: "Aggiungi attività", save: "Salva", cancel: "Annulla",
    noChallenges: "Nessuna sfida ancora.\nVisita la Comunità!",
    communitySubtitle: "Condividi i tuoi successi, trova la tua tribù",
    newPost: "Nuovo post", activityFeed: "Attività", challenges: "Sfide",
    participants: "partecipanti", joined: "Iscritto", join: "Iscriviti",
    newPostPlaceholder: "Condividi la tua vittoria, progresso o consiglio...",
    category: "Categoria", publishPost: "Pubblica",
    comments: "Commenti", noCommentsYet: "Nessun commento ancora. Sii il primo!",
    writeComment: "Scrivi un commento...", you: "Tu", justNow: "Adesso",
    progressSubtitle: "Monitora la tua produttività nel tempo",
    overallCompletion: "Completamento totale",
    done: "Fatto", remaining: "Rimasto", total: "Totale",
    byCategory: "Per categoria", aiInsights: "Analisi IA",
    noTaskData: "Nessun dato per questo periodo.\nAggiungi attività nella scheda Piano!",
  },
  tr: {
    plan: "Plan", progress: "İlerleme", community: "Topluluk", profile: "Profil",
    daily: "Günlük", weekly: "Haftalık", monthly: "Aylık", yearly: "Yıllık",
    noTasks: "Henüz görev yok", addFirst: "İlk görevini eklemek için + simgesine bas",
    inProgress: "Devam Ediyor", completed: "Tamamlandı",
    tasksCompleted: "görev tamamlandı", of: "/",
    dailyMotivation: "Günlük Motivasyon", all: "Tümü",
    achievements: "Başarımlar", communityChallenges: "Topluluk Görevleri",
    notifications: "Bildirimler", pushNotifications: "Anlık Bildirimler",
    alarmSound: "Alarm Sesi", appearance: "Görünüm",
    theme: "Tema", language: "Dil", partners: "Ortaklar",
    data: "Veriler", clearAllData: "Tüm Verileri Sil",
    tasksDone: "Yapılan", dayStreak: "Gün Serisi", completion: "Tamamlama",
    chooseTheme: "Tema Seç", chooseLanguage: "Dil Seç",
    addTask: "Görev Ekle", save: "Kaydet", cancel: "İptal",
    noChallenges: "Henüz görev yok.\nTopluluk'u ziyaret et!",
    communitySubtitle: "Başarılarını paylaş, kabileni bul",
    newPost: "Yeni Gönderi", activityFeed: "Akış", challenges: "Görevler",
    participants: "katılımcı", joined: "Katıldı", join: "Katıl",
    newPostPlaceholder: "Kazanımını, ilerleni veya ipucunu paylaş...",
    category: "Kategori", publishPost: "Yayınla",
    comments: "Yorumlar", noCommentsYet: "Henüz yorum yok. İlk sen ol!",
    writeComment: "Yorum yaz...", you: "Sen", justNow: "Şimdi",
    progressSubtitle: "Zaman içindeki üretkenliğini takip et",
    overallCompletion: "Genel Tamamlama",
    done: "Bitti", remaining: "Kalan", total: "Toplam",
    byCategory: "Kategoriye Göre", aiInsights: "AI Analizi",
    noTaskData: "Bu dönem için veri yok.\nPlan sekmesine görev ekle!",
  },
  az: {
    plan: "Plan", progress: "İrəliləyiş", community: "İcma", profile: "Profil",
    daily: "Günlük", weekly: "Həftəlik", monthly: "Aylıq", yearly: "İllik",
    noTasks: "Hələ tapşırıq yoxdur", addFirst: "İlk tapşırığı əlavə etmək üçün + basın",
    inProgress: "Davam Edir", completed: "Tamamlandı",
    tasksCompleted: "tapşırıq tamamlandı", of: "/",
    dailyMotivation: "Günlük Motivasiya", all: "Hamısı",
    achievements: "Nailiyyətlər", communityChallenges: "İcma Tapşırıqları",
    notifications: "Bildirişlər", pushNotifications: "Push Bildirişlər",
    alarmSound: "Zəng Səsi", appearance: "Görünüş",
    theme: "Mövzu", language: "Dil", partners: "Tərəfdaşlar",
    data: "Məlumatlar", clearAllData: "Bütün məlumatları sil",
    tasksDone: "Edildi", dayStreak: "Gün Seriyası", completion: "Tamamlanma",
    chooseTheme: "Mövzu Seç", chooseLanguage: "Dil Seç",
    addTask: "Tapşırıq Əlavə Et", save: "Saxla", cancel: "Ləğv et",
    noChallenges: "Hələ tapşırıq yoxdur.\nİcmanı ziyarət edin!",
    communitySubtitle: "Uğurlarınızı bölüşün, qrupunuzu tapın",
    newPost: "Yeni Göndəri", activityFeed: "Axın", challenges: "Tapşırıqlar",
    participants: "iştirakçı", joined: "Qoşuldu", join: "Qoşul",
    newPostPlaceholder: "Qazanımınızı, irəliləyişinizi və ya məsləhətinizi bölüşün...",
    category: "Kateqoriya", publishPost: "Yayımla",
    comments: "Şərhlər", noCommentsYet: "Hələ şərh yoxdur. İlk siz olun!",
    writeComment: "Şərh yazın...", you: "Siz", justNow: "İndi",
    progressSubtitle: "Zaman keçdikcə məhsuldarlığınızı izləyin",
    overallCompletion: "Ümumi Tamamlanma",
    done: "Hazır", remaining: "Qalan", total: "Cəmi",
    byCategory: "Kateqoriyaya görə", aiInsights: "AI Təhlili",
    noTaskData: "Bu dövr üçün məlumat yoxdur.\nPlan bölməsinə tapşırıq əlavə edin!",
  },
  ja: {
    plan: "プラン", progress: "進捗", community: "コミュニティ", profile: "プロフィール",
    daily: "毎日", weekly: "毎週", monthly: "毎月", yearly: "毎年",
    noTasks: "タスクがありません", addFirst: "+ をタップして最初のタスクを追加",
    inProgress: "進行中", completed: "完了",
    tasksCompleted: "タスク完了", of: "/",
    dailyMotivation: "今日の名言", all: "すべて",
    achievements: "実績", communityChallenges: "コミュニティチャレンジ",
    notifications: "通知", pushNotifications: "プッシュ通知",
    alarmSound: "アラーム音", appearance: "外観",
    theme: "テーマ", language: "言語", partners: "パートナー",
    data: "データ", clearAllData: "全データを削除",
    tasksDone: "完了タスク", dayStreak: "連続日数", completion: "達成率",
    chooseTheme: "テーマを選択", chooseLanguage: "言語を選択",
    addTask: "タスクを追加", save: "保存", cancel: "キャンセル",
    noChallenges: "まだ参加していません。\nコミュニティをチェック！",
    communitySubtitle: "成果を共有し、仲間を見つけよう",
    newPost: "新しい投稿", activityFeed: "アクティビティ", challenges: "チャレンジ",
    participants: "人が参加", joined: "参加済み", join: "参加",
    newPostPlaceholder: "成果、進捗、またはヒントを共有...",
    category: "カテゴリ", publishPost: "投稿",
    comments: "コメント", noCommentsYet: "まだコメントがありません。最初に投稿しよう！",
    writeComment: "コメントを書く...", you: "自分", justNow: "たった今",
    progressSubtitle: "時間経過とともに生産性を追跡",
    overallCompletion: "全体達成率",
    done: "完了", remaining: "残り", total: "合計",
    byCategory: "カテゴリ別", aiInsights: "AI インサイト",
    noTaskData: "この期間のデータがありません。\nプランタブにタスクを追加！",
  },
  ko: {
    plan: "플랜", progress: "진행", community: "커뮤니티", profile: "프로필",
    daily: "매일", weekly: "매주", monthly: "매월", yearly: "매년",
    noTasks: "아직 할 일이 없습니다", addFirst: "+ 를 눌러 첫 번째 할 일 추가",
    inProgress: "진행 중", completed: "완료",
    tasksCompleted: "개 완료", of: "/",
    dailyMotivation: "오늘의 명언", all: "전체",
    achievements: "업적", communityChallenges: "커뮤니티 챌린지",
    notifications: "알림", pushNotifications: "푸시 알림",
    alarmSound: "알람 소리", appearance: "외관",
    theme: "테마", language: "언어", partners: "파트너",
    data: "데이터", clearAllData: "모든 데이터 삭제",
    tasksDone: "완료한 일", dayStreak: "연속 일수", completion: "달성률",
    chooseTheme: "테마 선택", chooseLanguage: "언어 선택",
    addTask: "할 일 추가", save: "저장", cancel: "취소",
    noChallenges: "아직 참여한 챌린지가 없습니다.\n커뮤니티를 방문하세요!",
    communitySubtitle: "성과를 공유하고 동료를 찾으세요",
    newPost: "새 게시물", activityFeed: "활동", challenges: "챌린지",
    participants: "명 참여", joined: "참여 중", join: "참여",
    newPostPlaceholder: "성과, 진행 상황 또는 팁을 공유하세요...",
    category: "카테고리", publishPost: "게시",
    comments: "댓글", noCommentsYet: "아직 댓글이 없습니다. 첫 번째가 되세요!",
    writeComment: "댓글 작성...", you: "나", justNow: "방금",
    progressSubtitle: "시간별 생산성 추적",
    overallCompletion: "전체 달성률",
    done: "완료", remaining: "남음", total: "합계",
    byCategory: "카테고리별", aiInsights: "AI 인사이트",
    noTaskData: "이 기간의 데이터가 없습니다.\n플랜 탭에서 할 일을 추가하세요!",
  },
  id: {
    plan: "Rencana", progress: "Kemajuan", community: "Komunitas", profile: "Profil",
    daily: "Harian", weekly: "Mingguan", monthly: "Bulanan", yearly: "Tahunan",
    noTasks: "Belum ada tugas", addFirst: "Ketuk + untuk menambah tugas pertama",
    inProgress: "Sedang Berjalan", completed: "Selesai",
    tasksCompleted: "tugas selesai", of: "dari",
    dailyMotivation: "Motivasi Hari Ini", all: "Semua",
    achievements: "Pencapaian", communityChallenges: "Tantangan Komunitas",
    notifications: "Notifikasi", pushNotifications: "Notifikasi Push",
    alarmSound: "Suara Alarm", appearance: "Tampilan",
    theme: "Tema", language: "Bahasa", partners: "Mitra",
    data: "Data", clearAllData: "Hapus Semua Data",
    tasksDone: "Tugas Selesai", dayStreak: "Hari Beruntun", completion: "Penyelesaian",
    chooseTheme: "Pilih Tema", chooseLanguage: "Pilih Bahasa",
    addTask: "Tambah Tugas", save: "Simpan", cancel: "Batal",
    noChallenges: "Belum ada tantangan.\nKunjungi Komunitas!",
    communitySubtitle: "Bagikan kemenangan, temukan komunitasmu",
    newPost: "Postingan Baru", activityFeed: "Aktivitas", challenges: "Tantangan",
    participants: "peserta", joined: "Bergabung", join: "Gabung",
    newPostPlaceholder: "Bagikan kemenangan, kemajuan, atau tips...",
    category: "Kategori", publishPost: "Publikasikan",
    comments: "Komentar", noCommentsYet: "Belum ada komentar. Jadilah yang pertama!",
    writeComment: "Tulis komentar...", you: "Kamu", justNow: "Baru saja",
    progressSubtitle: "Lacak produktivitas dari waktu ke waktu",
    overallCompletion: "Penyelesaian Keseluruhan",
    done: "Selesai", remaining: "Tersisa", total: "Total",
    byCategory: "Per Kategori", aiInsights: "Wawasan AI",
    noTaskData: "Belum ada data untuk periode ini.\nTambah tugas di tab Rencana!",
  },
  uz: {
    plan: "Reja", progress: "Ilgarilanish", community: "Jamiyat", profile: "Profil",
    daily: "Kunlik", weekly: "Haftalik", monthly: "Oylik", yearly: "Yillik",
    noTasks: "Hali vazifalar yo'q", addFirst: "Birinchi vazifani qo'shish uchun + bosing",
    inProgress: "Bajarilmoqda", completed: "Bajarildi",
    tasksCompleted: "ta vazifa bajarildi", of: "/",
    dailyMotivation: "Kunlik ilhom", all: "Barchasi",
    achievements: "Yutuqlar", communityChallenges: "Jamiyat topshiriqlari",
    notifications: "Bildirishnomalar", pushNotifications: "Push bildirishnomalar",
    alarmSound: "Soat ovozi", appearance: "Ko'rinish",
    theme: "Mavzu", language: "Til", partners: "Hamkorlar",
    data: "Ma'lumotlar", clearAllData: "Barcha ma'lumotlarni o'chirish",
    tasksDone: "Bajarilgan", dayStreak: "Kun seriyasi", completion: "Bajarilish",
    chooseTheme: "Mavzu tanlash", chooseLanguage: "Til tanlash",
    addTask: "Vazifa qo'shish", save: "Saqlash", cancel: "Bekor qilish",
    noChallenges: "Hali topshiriqlar yo'q.\nJamiyatga tashrif buyuring!",
    communitySubtitle: "Yutuqlaringizni ulashing, guruhingizni toping",
    newPost: "Yangi post", activityFeed: "Faoliyat", challenges: "Topshiriqlar",
    participants: "ishtirokchi", joined: "Qo'shildi", join: "Qo'shilish",
    newPostPlaceholder: "G'alabangiz, natijangiz yoki maslahatingiznı ulashing...",
    category: "Kategoriya", publishPost: "Nashr qilish",
    comments: "Izohlar", noCommentsYet: "Hali izoh yo'q. Birinchi bo'ling!",
    writeComment: "Izoh yozing...", you: "Siz", justNow: "Hozir",
    progressSubtitle: "Vaqt o'tishi bilan samaradorligingizni kuzating",
    overallCompletion: "Umumiy bajarilish",
    done: "Bajarildi", remaining: "Qolgan", total: "Jami",
    byCategory: "Kategoriya bo'yicha", aiInsights: "AI tahlili",
    noTaskData: "Bu davr uchun ma'lumot yo'q.\nReja bo'limiga vazifa qo'shing!",
  },
  kk: {
    plan: "Жоспар", progress: "Үдеріс", community: "Қоғам", profile: "Профиль",
    daily: "Күнделікті", weekly: "Апталық", monthly: "Айлық", yearly: "Жылдық",
    noTasks: "Тапсырма жоқ", addFirst: "Бірінші тапсырманы қосу үшін + басыңыз",
    inProgress: "Орындалуда", completed: "Аяқталды",
    tasksCompleted: "тапсырма орындалды", of: "/",
    dailyMotivation: "Күнделікті шабыт", all: "Барлығы",
    achievements: "Жетістіктер", communityChallenges: "Қоғам тапсырмалары",
    notifications: "Хабарландырулар", pushNotifications: "Push хабарландырулар",
    alarmSound: "Дабыл дыбысы", appearance: "Көрініс",
    theme: "Тақырып", language: "Тіл", partners: "Серіктестер",
    data: "Деректер", clearAllData: "Барлық деректерді жою",
    tasksDone: "Орындалған", dayStreak: "Күн сериясы", completion: "Орындалу",
    chooseTheme: "Тақырып таңдау", chooseLanguage: "Тіл таңдау",
    addTask: "Тапсырма қосу", save: "Сақтау", cancel: "Бас тарту",
    noChallenges: "Тапсырмалар жоқ.\nҚоғамға кіріңіз!",
    communitySubtitle: "Жетістіктеріңізді бөлісіңіз, топ табыңыз",
    newPost: "Жаңа жазба", activityFeed: "Белсенділік", challenges: "Тапсырмалар",
    participants: "қатысушы", joined: "Қосылды", join: "Қосылу",
    newPostPlaceholder: "Жеңісіңізді, нәтижеңізді немесе кеңесіңізді бөлісіңіз...",
    category: "Санат", publishPost: "Жариялау",
    comments: "Пікірлер", noCommentsYet: "Пікір жоқ. Бірінші болыңыз!",
    writeComment: "Пікір жазыңыз...", you: "Сіз", justNow: "Қазір",
    progressSubtitle: "Уақыт өте келе өнімділікті бақылаңыз",
    overallCompletion: "Жалпы орындалу",
    done: "Дайын", remaining: "Қалды", total: "Барлығы",
    byCategory: "Санат бойынша", aiInsights: "AI талдауы",
    noTaskData: "Бұл кезең үшін деректер жоқ.\nЖоспар бөліміне тапсырма қосыңыз!",
  },
  ky: {
    plan: "Пландоо", progress: "Прогресс", community: "Коомдошток", profile: "Профиль",
    daily: "Күнүмдүк", weekly: "Жумалык", monthly: "Айлык", yearly: "Жылдык",
    noTasks: "Тапшырма жок", addFirst: "Биринчи тапшырманы кошуу үчүн + басыңыз",
    inProgress: "Аткарылуда", completed: "Аяктады",
    tasksCompleted: "тапшырма аяктады", of: "/",
    dailyMotivation: "Күнүмдүк шыктандыруу", all: "Баары",
    achievements: "Жетишкендиктер", communityChallenges: "Коомдоштук тапшырмалары",
    notifications: "Билдирүүлөр", pushNotifications: "Push билдирүүлөр",
    alarmSound: "Ойготкуч үнү", appearance: "Көрүнүш",
    theme: "Тема", language: "Тил", partners: "Өнөктөштөр",
    data: "Маалыматтар", clearAllData: "Бардык маалыматтарды жок кылуу",
    tasksDone: "Аткарылган", dayStreak: "Күн сериясы", completion: "Аткаруу",
    chooseTheme: "Тема тандоо", chooseLanguage: "Тил тандоо",
    addTask: "Тапшырма кошуу", save: "Сактоо", cancel: "Жокко чыгаруу",
    noChallenges: "Тапшырмалар жок.\nКоомдоштукка кириңиз!",
    communitySubtitle: "Жетишкендиктериңизди бөлүшүңүз, топ табыңыз",
    newPost: "Жаңы жазуу", activityFeed: "Активдүүлүк", challenges: "Тапшырмалар",
    participants: "катышуучу", joined: "Кошулду", join: "Кошулуу",
    newPostPlaceholder: "Жеңишиңизди, жыйынтыгыңызды же кеңешиңизди бөлүшүңүз...",
    category: "Категория", publishPost: "Жарыялоо",
    comments: "Комментарийлер", noCommentsYet: "Комментарий жок. Биринчи болуңуз!",
    writeComment: "Комментарий жазыңыз...", you: "Сиз", justNow: "Азыр",
    progressSubtitle: "Убакыт өткөн сайын өндүрүмдүүлүктү көзөмөлдөңүз",
    overallCompletion: "Жалпы аткаруу",
    done: "Бүттү", remaining: "Калды", total: "Баары",
    byCategory: "Категория боюнча", aiInsights: "AI талдоо",
    noTaskData: "Бул мезгил үчүн маалымат жок.\nПландоо бөлүмүнө тапшырма кошуңуз!",
  },
  tg: {
    plan: "Нақша", progress: "Пешрафт", community: "Ҷамоат", profile: "Профил",
    daily: "Ҳаррӯза", weekly: "Ҳафтагӣ", monthly: "Моҳона", yearly: "Солона",
    noTasks: "Вазифаҳо нест", addFirst: "Барои илова кардани вазифа + -ро зер кунед",
    inProgress: "Иҷро мешавад", completed: "Анҷом ёфт",
    tasksCompleted: "вазифа анҷом ёфт", of: "/",
    dailyMotivation: "Илҳоми рӯзона", all: "Ҳама",
    achievements: "Дастовардҳо", communityChallenges: "Супоришҳои ҷамоат",
    notifications: "Огоҳиҳо", pushNotifications: "Push огоҳиҳо",
    alarmSound: "Овози зангӯлак", appearance: "Зоҳир",
    theme: "Мавзӯъ", language: "Забон", partners: "Шарикон",
    data: "Маълумот", clearAllData: "Ҳама маълумотро тоза кунед",
    tasksDone: "Иҷро шуд", dayStreak: "Рӯзҳои пайдарпай", completion: "Иҷро",
    chooseTheme: "Мавзӯъ интихоб кунед", chooseLanguage: "Забон интихоб кунед",
    addTask: "Вазифа илова кунед", save: "Сохтан", cancel: "Бекор кардан",
    noChallenges: "Супоришҳо нест.\nАз Ҷамоат дидан кунед!",
    communitySubtitle: "Муваффақиятҳоятонро мубодила кунед",
    newPost: "Паёми нав", activityFeed: "Фаъолият", challenges: "Супоришҳо",
    participants: "иштирокчӣ", joined: "Ҳамроҳ шуд", join: "Ҳамроҳ шавед",
    newPostPlaceholder: "Муваффақият, пешрафт ё маслиҳататонро мубодила кунед...",
    category: "Категория", publishPost: "Нашр кунед",
    comments: "Шарҳҳо", noCommentsYet: "Ҳоло шарҳе нест. Аввалин шавед!",
    writeComment: "Шарҳ нависед...", you: "Шумо", justNow: "Ҳозир",
    progressSubtitle: "Самаранокиятонро дар тӯли вақт пайгирӣ кунед",
    overallCompletion: "Иҷрои умумӣ",
    done: "Тайёр", remaining: "Боқӣ", total: "Ҳама",
    byCategory: "Аз рӯи категория", aiInsights: "Таҳлили AI",
    noTaskData: "Барои ин давра маълумот нест.\nБа нақша вазифа илова кунед!",
  },
  tk: {
    plan: "Meýilnama", progress: "Öňe gidiş", community: "Jemgyýet", profile: "Profil",
    daily: "Gündelik", weekly: "Hepdelik", monthly: "Aýlyk", yearly: "Ýyllyk",
    noTasks: "Wezipeler ýok", addFirst: "Ilkinji wezipe goşmak üçin + basyň",
    inProgress: "Ýerine ýetirilýär", completed: "Tamamlandy",
    tasksCompleted: "wezipe tamamlandy", of: "/",
    dailyMotivation: "Gündelik ylham", all: "Hemmesi",
    achievements: "Üstünlikler", communityChallenges: "Jemgyýet wezipeleri",
    notifications: "Habarnamalar", pushNotifications: "Push habarnamalar",
    alarmSound: "Duýduryş sesi", appearance: "Görünüş",
    theme: "Tema", language: "Dil", partners: "Hyzmatdaşlar",
    data: "Maglumat", clearAllData: "Ähli maglumatlary pozmak",
    tasksDone: "Ýerine ýetirildi", dayStreak: "Gün yzygiderliligi", completion: "Tamamlanyş",
    chooseTheme: "Tema saýlaň", chooseLanguage: "Dil saýlaň",
    addTask: "Wezipe goşuň", save: "Saklamak", cancel: "Ýatyrmak",
    noChallenges: "Wezipeler ýok.\nJemgyýete baryň!",
    communitySubtitle: "Üstünlikleriňizi paýlaşyň, toparňyzy tapyň",
    newPost: "Täze ýazgy", activityFeed: "Işjeňlik", challenges: "Wezipeler",
    participants: "gatnaşyjy", joined: "Goşuldy", join: "Goşulmak",
    newPostPlaceholder: "Üstünligiňizi, öňe gidişiňizi ýa-da maslahatlaryňyzy paýlaşyň...",
    category: "Kategoriýa", publishPost: "Çap etmek",
    comments: "Teswirler", noCommentsYet: "Heniz teswir ýok. Ilkinji boluň!",
    writeComment: "Teswir ýazyň...", you: "Siz", justNow: "Häzir",
    progressSubtitle: "Wagtyň geçmegi bilen önümçiligi yzarlaň",
    overallCompletion: "Umumy tamamlanyş",
    done: "Taýyn", remaining: "Galan", total: "Jemi",
    byCategory: "Kategoriýa boýunça", aiInsights: "AI derňewi",
    noTaskData: "Bu döwür üçin maglumat ýok.\nMeýilnama sekmesine wezipe goşuň!",
  },
};

type ThemeContextType = {
  themeMode: ThemeMode;
  language: Language;
  isDark: boolean;
  setThemeMode: (mode: ThemeMode) => void;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
};

const ThemeContext = createContext<ThemeContextType | null>(null);

export function ThemeProvider({ children }: { children: React.ReactNode }) {
  const systemScheme = useColorScheme();
  const [themeMode, setThemeModeState] = useState<ThemeMode>("system");
  const [language, setLanguageState] = useState<Language>("en");

  useEffect(() => {
    AsyncStorage.multiGet(["themeMode", "language"]).then((pairs) => {
      const tm = pairs[0][1] as ThemeMode | null;
      const lang = pairs[1][1] as Language | null;
      if (tm) setThemeModeState(tm);
      if (lang) setLanguageState(lang as Language);
    });
  }, []);

  const setThemeMode = useCallback((mode: ThemeMode) => {
    setThemeModeState(mode);
    AsyncStorage.setItem("themeMode", mode);
  }, []);

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    AsyncStorage.setItem("language", lang);
  }, []);

  const isDark =
    themeMode === "dark" || (themeMode === "system" && systemScheme === "dark");

  const t = useCallback(
    (key: string) => {
      return TRANSLATIONS[language]?.[key] ?? TRANSLATIONS.en[key] ?? key;
    },
    [language]
  );

  return (
    <ThemeContext.Provider value={{ themeMode, language, isDark, setThemeMode, setLanguage, t }}>
      {children}
    </ThemeContext.Provider>
  );
}

export function useTheme() {
  const ctx = useContext(ThemeContext);
  if (!ctx) throw new Error("useTheme must be used within ThemeProvider");
  return ctx;
}
